### ISSUE TITLE
emojipaper command - suggestion

### ISSUE THREAD

**Issue by c291bGxlc3Nzb29vZXM** [megaboi2005/wearybot#3]
posts this image https://neoncolorslol.neocities.org/images/dghdddhh.png

**Comment by megaboi2005** [comment]
one question, *why*

**Comment by c291bGxlc3Nzb29vZXM** [comment]
to question all.

**Comment by megaboi2005** [comment]
![](https://neoncolorslol.neocities.org/images/dghdddhh.png)
me when I see this issue

**Comment by c291bGxlc3Nzb29vZXM** [comment]
ok thanks
